/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./frontend/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffddd5",
        "on-background": "#191b25",
        "tertiary-fixed-dim": "#ffb4a1",
        outline: "#737688",
        "tertiary-fixed": "#ffdbd2",
        "surface-bright": "#fbf8ff",
        "on-error": "#ffffff",
        surface: "#fbf8ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#dfe3ff",
        "secondary-fixed": "#dde1ff",
        "surface-tint": "#004ced",
        "on-tertiary-fixed": "#3c0800",
        "on-primary-fixed": "#001452",
        "surface-container-highest": "#e1e1ef",
        "on-surface-variant": "#434656",
        background: "#fbf8ff",
        "error-container": "#ffdad6",
        "on-surface": "#191b25",
        "surface-container-high": "#e7e7f5",
        "secondary-container": "#95aafe",
        "on-secondary-fixed": "#001452",
        "on-primary-fixed-variant": "#0038b6",
        "surface-container": "#ededfb",
        secondary: "#4459a8",
        "on-secondary-container": "#253b89",
        "on-secondary-fixed-variant": "#2b418f",
        "inverse-primary": "#b7c4ff",
        "tertiary-container": "#bf3003",
        "outline-variant": "#c3c5d9",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e303a",
        "on-tertiary-fixed-variant": "#891e00",
        "secondary-fixed-dim": "#b7c4ff",
        "surface-container-low": "#f3f2ff",
        "inverse-on-surface": "#f0effe",
        "surface-variant": "#e1e1ef",
        "on-tertiary": "#ffffff",
        tertiary: "#952200",
        "surface-dim": "#d9d9e7",
        "primary-fixed": "#dde1ff",
        "primary-container": "#0052ff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        primary: "#003ec7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
